baseURL: https://beatriznarciso.netlify.app/
languageCode: en-us
title: Portfolio Website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Enjoy!
    subtitle: |-
      The original webiste into the life of Beatriz. 
    title: Beatriz Narciso
  blog: {}
  contact:
    address:
      - city: London  
        country: United Kingdom
        street: 
        title: 
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: mbeatriznarciso@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: "+44 7883034284"
        title: #
  custom_css: []
  custom_js: []
  description: 
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/mbeatriznarciso/
      - icon: fa-github
        label: GitHub
        url: https://github.com/beatriznarciso
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/mbeatriznarciso/
  image: ''
  name: "Beatriz Narciso"
  navigation:
    button1:
      - name: See more
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: Born and raised in Lisbon
        title: Portugal
        url: blogs/aliquam
      - image: pic02.jpg
        subtitle: How to make the most out of your exchange semester
        title: South Korea
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Being a student in London
        title: United Kingdom
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Get to know more about London Business School
        title: Student Amabassador
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
      
  two:
    buttonText: Find out more
    enable: yes
    subtitle: My name is Maria Beatriz but please feel free to call me Bia. I'm a currently studying at LBS, doing the Masters in Financial Analysis.I consider myself to be a very passionate and enthusiastic person who enjoys a good challenge."
    title: Who am I
    url: blogs
