baseURL: https://beatriznarciso.netlify.app/
languageCode: en-us
title: Portfolio Website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Enjoy!
    subtitle: |-
      The original webiste into the life of Beatriz. 
    title: Beatriz Narciso
  blog: {}
  contact:
    address:
      - city: London  
        country: United Kingdom
        street: 
        title: 
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: mbeatriznarciso@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: "+44 7883034284"
        title: #
  custom_css: []
  custom_js: []
  description: 
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/mbeatriznarciso/
      - icon: fa-github
        label: GitHub
        url: https://github.com/beatriznarciso
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/mbeatriznarciso/
  image: ''
  name: "Beatriz Narciso"
  navigation:
    button1:
      - name: See more
        url: blogs
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: 
        subtitle: Born and raised in Lisbon
        title: A bit about myself
        url: blogs/Lisbon
      - image: 
        subtitle: Why should we care?
        title: Global Warming
        url: blogs/environment
      - image: 
        subtitle: What is better than a movie and popcorns?
        title: Movies
        url: blogs/movies
      - image: 
        subtitle: Get to know more about London Business School
        title: Student Amabassador
        url: blogs/lbs-community
   two:
    buttonText: Find out more
    enable: yes
    subtitle: My name is Maria Beatriz but please feel free to call me Bia. I'm a currently studying at LBS, doing the Masters in Financial Analysis. I consider myself to be a very passionate and enthusiastic person who enjoys a good challenge. Outside the walls of Sussex Place or Sammy Offer I have a hate-love raltioship with jogging, I love to travel and I am the biggest foodie!
    title: Who am I?
    url: blogs
